name: XcodeBuildCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.3,name=iPhone 12 Pro Max']
    
    steps:
    - uses: actions/checkout@v2
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.3.app
    - name: Build
      run: |
        xcodebuild clean build -project SecureEnclave.xcodeproj -scheme SecureEnclave -destination "${{ matrix.destination }}"
